config/routes.rb
Rails.application.routes.draw do
  # scope "(:locale)", locale: /en|vi/ do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  as :user do
    get "sign_in" => "users/sessions#new"
    post "sign_in" => "users/sessions#create"
    get "sign_up" => "users/registrations#new"
    post "sign_up" => "users/registrations#create"
    get "sign_out" => "users/sessions#destroy"
    get "change_pw" => "users/passwords#edit"
    put "change_pw" => "users/passwords#update"
  end


  devise_scope :user do

    authenticated :user do
      root 'employee#index', as: :authenticated_root
      get "sign_out" => "devise/sessions#destroy"

      resources 'departments'

      resources 'projects'

      resources 'employees' do


        # member do
        #  /id cho method
        # end
        #
        collection do

        end
      end


      # get 'epl/list' => 'employee#list'
      # get 'epl/new' => 'employee#new'
      # post 'epl/create' => 'employee#create'
      # get 'epl/show' => 'employee#show'
      # patch 'epl/update' => 'employee#update'
      # get 'epl/update' => 'employee#update'
      # get 'epl/edit' => 'employee#edit'
      # get 'epl/delete' => 'employee#delete'
      # get 'epl/info' => 'employee#info'


      get 'user/list' => 'user#list'
      get 'user/delete' => 'user#delete'

      resources 'employee_project'
      # get 'employee_project/delete' => 'employee_project#destroy'
    end

    unauthenticated do
      root 'users/sessions#new', as: :unauthenticated_root
    end
  end
  # devise_for :users
  # root "employee#index"
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HRM</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
</head>
<body>
<div class="container-fluid">
  <p class="notice", style="color: green"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/layouts/dashboard.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HRM</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-fQybjgWLrvvRgtW6bFlB7jaZrFsaBXjsOMm/tB9LTS58ONXgqbR9W8oWht/amnpF" crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css" integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
  <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet"/>
  <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
</head>
<body>
<div class="container-fluid">
  <nav class="navbar navbar-expand-lg  fixed-top", style="background-color: aliceblue">
    <div class="container-fluid">
      <%= link_to 'Trang chủ', authenticated_root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if policy(:user).list? %>
            <li class="nav-item">
              <%= link_to 'Dự án', projects_path, class: "nav-link active" %>
            </li>
          <% end %>
          <% if policy(:department).index? %>
            <li class="nav-item">
              <%= link_to 'Phòng ban', departments_path, class: "nav-link active" %>
            </li>
          <% end %>
          <% if policy(:employee).list? %>
            <li class="nav-item">
              <%= link_to 'Nhân viên', epl_list_path, class: "nav-link active" %>
            </li>
          <% end %>
          <% if policy(:user).list? %>
            <li class="nav-item">
              <%= link_to 'Tài khoản', user_list_path, class: "nav-link active" %>
            </li>
          <% end %>
          <li class="nav-item dropdown">
            <span class="nav-link nav-link dropdown-toggle navbarDropdown " role="button" data-toggle="dropdown" aria-expanded="false">
              <% if current_user.employee.present? %>
              Xin chào <%= current_user.employee.name %>
                <% else %>
              <p>Bạn cần điền đầy đủ thông tin cho email này</p>
                <% end %>
            </span>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Thong tin ca nhan", epl_info_path, class: "dropdown-item" %>
              <%= link_to "Doi mat khau", change_pw_path, class: "dropdown-item" %>
              <%= link_to "Dang xuat", sign_out_path, class: "dropdown-item" %>
            </div>
            <!--          <li class="nav-item">-->
            <%#= link_to 'Đăng Kí', sign_up_path, class: "nav-link active" %>
            <!--          </li>-->
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <p class="notice", style="color: green"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

<div class="container" style="margin-top: 5%">
  <% if flash.any? %>
    <% flash.each do |type, msg| %>
      <div>
        <%= msg %>
      </div>
    <% end %>
  <% end %>
  <%= yield %>
</div>
<footer class="text-center text-white fixed-bottom">

  <!-- Copyright -->
  <div class="text-center p-3" style="background-color: aliceblue">
    <a class="text-blue" href="https://bnksolution.com/">© 2020 Copyright: Bnk Solution - Phần mềm quản lý nhân sự Version 0.1</a>
  </div>
  <!-- Copyright -->
</footer>
</body>
</html>

app/views/layouts/header.html.erb
<div class="container-fluid">
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <%= link_to 'Trang chủ', authenticated_root_path, class: "navbar-brand" %>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to 'Dự án', prj_list_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Phòng ban', dpms_list_path, class: "nav-link active" %>
          <li class="nav-item">
            <%= link_to 'Nhân viên', epl_list_path, class: "nav-link active" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Tài khoản', user_list_path, class: "nav-link active" %>
          </li>
          <li class="nav-item dropdown">
            <span class="nav-link nav-link dropdown-toggle navbarDropdown "  role="button" data-toggle="dropdown" aria-expanded="false">
              <% if current_user.employee.present?  %>
              Xin chào <%= current_user.employee.name%>
                <% end %>
            </span>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to "Thong tin ca nhan", epl_info_path, class: "dropdown-item" %>
              <%= link_to "Doi mat khau", change_pw_path  ,class: "dropdown-item" %>
              <%= link_to "Dang xuat", sign_out_path, class: "dropdown-item" %>
            </div>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <p class="notice", style="color: green"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>